on:
  - push
  - workflow_dispatch

jobs:
  build:
    if: ${{ endsWith(github.event.commits[0].message, '[release]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Packages
        run: npm ci
      - name: Test
        run: npm run test 30
      - name: Build For ${{ matrix.platform }}
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: bin/*

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login To NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}"  > ~/.npmrc
      - name: Publish To NPM
        run: |
          npm ci
          npm publish || echo
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: bin/
      - name: Get Release Name
        run: echo "::set-output name=VER::v$(node -p "require('./package.json').version")"
        id: VER
      - name: Remove Previous Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ steps.VER.outputs.VER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/**/*
          tag: ${{ steps.VER.outputs.VER }}
          overwrite: true
          file_glob: true
          body: ''
